//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#RE_IN_DE
#pragma define (store)
#if _LSL_COMPILERVERSION >= 42
_OpenSSL : CLASS;
HwcLogging : CLASS;
OPC_UA_Base : CLASS;
OPC_UA_ModuleBase : CLASS;
SigCLib : CLASS;
StringInternal : CLASS;
#endif
#pragma InclDefBlk SdiasBase
SdiasBase : CLASS_PUBLIC
#include "..\Class\SdiasManager\SdiasManager.h"
#include "..\Class\SdiasBase\SdiasBase.h"
#include "..\Class\HwControl\HwControl.h"
#include "..\Source\interfaces\lsl_st_hardwaretree.h"
#include "..\Source\interfaces\lsl_st_mt.h"
	TYPE
	  t_b_SdiasFWState : BINT
	  [
	    1 VoltageNotOk,
	    2 NoSync,
	    3 FlashDataCRCError,
	    4 RAMDataCRCError,
	    5 FlashUnsafe,
	    6 BusTimeNotSupported,
	    7 ToggleBit,
	  ];
#pragma pack(push, 1)
	  t_s_SdiasFWStateStandard : STRUCT
	    ErrorBits : t_b_SdiasFWState;
	    Reserved : UINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_s_SPI_AccessControl : STRUCT
	    udAccessHandle : UDINT;
	    usAccessLength : USINT;
	    usAccessOffset : USINT;
	    pControlByte : t_SDIAS_pControlByte;
	    pStateByte : t_SDIAS_pStateByte;
	  END_STRUCT;
#pragma pack(pop)
	  t_SPI_PDO_DataWrite : ARRAY [0..SDIAS_MAX_PDO_SIZE-1] OF USINT;
	  t_SPI_PDO_DataRead : ARRAY [0..SDIAS_MAX_PDO_SIZE-1] OF USINT;
	  t_e_SPIWriteSSW :
	  (
	    _SPIWrite_Idle,
	    _AllocateMemory,
	    _SetRequest,
	    _ReadGrant,
	    _ReadSectorData_SetPageAddress,
	    _ReadSectorData_Wait4SetPageAddress,
	    _ReadSectorData_SetReadPageCommand,
	    _ReadSectorData_Wait4SetReadPageCommand,
	    _ReadSectorData_ReadReceiveBufferPart1,
	    _ReadSectorData_ReadReceiveBufferPart2,
	    _EraseSector_SetPageAddress,
	    _EraseSector_Wait4SetPageAddress,
	    _EraseSector_SetEraseSectorCommand,
	    _EraseSector_Wait4SetEraseSectorCommand,
	    _WriteSectorData_SetPageAddress,
	    _WriteSectorData_Wait4SetPageAddress,
	    _WriteSectorData_WriteTransmitBufferPart1,
	    _WriteSectorData_WriteTransmitBufferPart2,
	    _WriteSectorData_SetWritePageCommand,
	    _WriteSectorData_Wait4SetWritePageCommand,
	    _VerifySectorData_SetPageAddress,
	    _VerifySectorData_Wait4SetPageAddress,
	    _VerifySectorData_SetReadPageCommand,
	    _VerifySectorData_Wait4SetReadPageCommand,
	    _VerifySectorData_ReadReceiveBufferPart1,
	    _VerifySectorData_ReadReceiveBufferPart2,
	    _VerifySectorData_CompareData,
	    _ClearRequest,
	    _DisableDataObjects,
	    _FreeMemory,
	    _FinishSPIWrite
	  )$UDINT;
	  usWriteModes : USINT;
#pragma pack(push, 1)
	  t_s_SPIWriteVars : STRUCT
	    sWriteAccess : t_s_SPI_AccessControl;
	    pWriteData : ^t_SPI_PDO_DataWrite;
	    sReadAccess : t_s_SPI_AccessControl;
	    pReadData : ^t_SPI_PDO_DataRead;
	    sReadStateAccess : t_s_SPI_AccessControl;
	    pReadStateData : ^USINT;
	    pSectorMemoryRead : ^USINT;
	    pSectorMemoryWrite : ^USINT;
	    pSectorMemoryVerify : ^USINT;
	    pUserWriteData : ^USINT;
	    udUserWriteLength : UDINT;
	    usUserSectorNumber : USINT;
	    usUserPageNumber : USINT;
	    usUserPageOffset : USINT;
	    eSPIWriteSSW : t_e_SPIWriteSSW;
	    eSPIWriteSSWError : t_e_SPIWriteSSW;
	    uiCurrentPage : UINT;
	    udCurrentSectorMemoryOffset : UDINT;
	    usRetryCnt : USINT;
	    bsFinished : BSINT
	    [
	      1 Finished,
	      2 Error,
	      3 Bit3,
	      4 Bit4,
	      5 Bit5,
	      6 Bit6,
	      7 Bit7,
	      8 Bit8,
	    ];
	    usCycleWaitCnt : USINT;
	    udTimeout : UDINT;
	    NotReadyCnt : DINT;
	    usFinishedWriteLog : USINT;
	    usWriteMode : usWriteModes;
	    udMemoryToAllocate : UDINT;
	    uiLastPage : UINT;
	    udUserDataOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _BusInterfaceSdiasDriveMng
_BusInterfaceSdiasDriveMng : CLASS_PUBLIC
: SdiasBase
#include "..\class\_drivemngbase\drivemngbase.h"
	TYPE
#pragma pack(push, 1)
	  t_ReadValuePtr : STRUCT
	    a_SyncValues : ARRAY [0..4] OF DINT;
	    bs_InputStates : BSINT
	    [
	      1 OptionBoardInputState,
	    ];
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_WriteValuePtr : STRUCT
	    a_SyncValues : ARRAY [0..4] OF DINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _DriveAxisBase
_DriveAxisBase : CLASS_PUBLIC
#include "..\Class\_DriveMngBase\SDDDefinitions.h"
#include "..\Class\HwControl\HwControl.h"
#include "..\Class\_DriveAxisBase\_DriveAxis_A_INT_Def.h"
	TYPE
#pragma pack(push, 1)
	  _SDDMEMHEADER : STRUCT
	    udCRC32 : UDINT;
	    udLen : UDINT;
	    udVersion : UDINT;
	    AxOffset : DINT;
	    AxLength : UDINT;
	    AxName : ARRAY [0..20] OF CHAR;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _DriveMngBase
_DriveMngBase : CLASS_PUBLIC
#include "..\Class\_DriveMngBase\SDDDefinitions.h"
#include "..\class\_drivemngbase\drivemngbase.h"
	TYPE
#pragma pack(push, 1)
	  _SDDBFENTRY : STRUCT
	    bFinished : DINT;
	    uiParaIndex : UINT;
	    usParaSubIndex : USINT;
	    usRDWR : USINT;
	    bsDataInfo : BSINT
	    [
	      1 DataLength1,
	      2 DataLength2,
	      3 res1,
	      4 res2,
	      5 Offset1,
	      6 Offset2,
	      7 res3,
	      8 res4,
	    ];
	    dValue : ARRAY [0..11] OF USINT;
	    pThisObj : ^void;
	    usEntry : USINT;
	    bSent : BOOL;
	    udTimeStamp : UDINT;
	    udTimeoutCycles : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _SDDRINGBUFFER : STRUCT
	    pStart : ^_SDDBFENTRY;
	    pEnd : ^_SDDBFENTRY;
	    pRead : ^_SDDBFENTRY;
	    pWrite : ^_SDDBFENTRY;
	    ActEntries : DINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
_SerLib : CLASS_PUBLIC
	TYPE
	  CmdCommand :
	  (
	    StartUserIPR,
	    StopUserIPR,
	    SerCloseIPR,
	    SerSendIPR,
	    RecvCharIPR,
	    SetOnlineIPR,
	    GetRecvStateIPR,
	    GetSendStateIPR,
	    GetErrorIPR,
	    IsInitializedIPR,
	    ClearRecBufferIPR,
	    RtsOnOffIPR,
	    rdRtsIPR,
	    rdCtsIPR,
	    DtrOnOffIPR,
	    rdDtrIPR,
	    rdDcdIPR,
	    rdDsrIPR,
	    rdRiIPR,
	    SetRSModeIPR,
	    GetRSModeIPR,
	    GetInterfaceTypeIPR
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _VaranDriveBase
_VaranDriveBase : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  t_ReadValuePtr : STRUCT
	    a_SyncValues : ARRAY [0..4] OF DINT;
	    bs_InputStates : BSINT
	    [
	      1 OptionBoardInputState,
	    ];
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_WriteValuePtr : STRUCT
	    a_SyncValues : ARRAY [0..4] OF DINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
ECAT_Master_Base : CLASS_PUBLIC
#include "..\Class\ECAT_Master_Base\ECAT_Master_Base.h"
#include "..\Source\BusInterface.h"
#include "..\Source\interfaces\lsl_st_hardwaretree.h"
#include "..\Class\HwControl\HwControl.h"
#include "..\Source\interfaces\lsl_st_ecatm.h"
#include "..\Source\interfaces\lsl_st_systrace.h"
	TYPE
#pragma pack(push, 1)
	  t_s_EtherCATFrameTimes : STRUCT
	    udEtherCATFrameTime : UDINT;
	    udEtherCATFrameTimeMin : UDINT;
	    udEtherCATFrameTimeMax : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
MerkerEx : CLASS_PUBLIC
#include <.\lsl_st_mt.h>
	TYPE
	  Cmdm_udLength :
	  (
	    GET_DATA_PTR,
	    EXCHANGE_DATA_PTR,
	    SAVE_DATA_TO_RAMEXFILE
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk OPC_UA
OPC_UA : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  int64 : STRUCT
	    low : UDINT;
	    high : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	  OPC_UA_SETPARAMETER :
	  (
	    OPC_UA_PAR_SET_DELAYTIME:=0,
	    OPC_UA_PAR_SET_THREADPRIO,
	    OPC_UA_PAR_SET_AUTOCERTIFNR,
	    OPC_UA_PAR_SET_DEDICATED_MEMORY_ENABLED,
	    OPC_UA_PAR_SET_TRACELEVEL_RESET_TIME
	  )$UDINT;
#pragma pack(push, 1)
	  tOPCUA_LocalizedText : STRUCT
	    Locale : ^CHAR;
	    Text : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
	  ptrLocalizedText : ^tOPCUA_LocalizedText;
	  ptrOpcUa_LocalizedText : ^tOPCUA_LocalizedText;
#pragma pack(push, 1)
	  tOpcUa_PkiCertificateInfo : STRUCT
	    sURI : ^CHAR;
	    sIP : ^CHAR;
	    sDNS : ^CHAR;
	    sEMail : ^CHAR;
	    validTime : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	  ptrOpcUa_PkiCertificateInfo : ^tOpcUa_PkiCertificateInfo;
#pragma pack(push, 1)
	  tOpcUa_PkiIdentity : STRUCT
	    sOrganization : ^CHAR;
	    sOrganizationUnit : ^CHAR;
	    sLocality : ^CHAR;
	    sState : ^CHAR;
	    sCountry : ^CHAR;
	    sCommonName : ^CHAR;
	    sDomainComponent : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
	  ptrOpcUa_PkiIdentity : ^tOpcUa_PkiIdentity;
#pragma pack(push, 1)
	  tOPCUA_String : STRUCT
	    Text : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
	  ptrOPCUA_String : ^tOPCUA_String;
#pragma pack(push, 1)
	  tOpcUa_Variant : STRUCT
	    DataType : UDINT;
	    ArrayType : OPCUA_ArrayType_Enum;
	    ArraySize : DINT;
	    Value : _PVOIDL;
	  END_STRUCT;
#pragma pack(pop)
	  ptrOpcUa_Variant : ^tOpcUa_Variant;
	  T_BITS : BDINT
	  [
	    1 Bit1,
	    2 Bit2,
	    3 Bit3,
	    4 Bit4,
	    5 Bit5,
	    6 Bit6,
	    7 Bit7,
	    8 Bit8,
	    9 Bit9,
	    10 Bit10,
	    11 Bit11,
	    12 Bit12,
	    13 Bit13,
	    14 Bit14,
	    15 Bit15,
	    16 Bit16,
	    17 Bit17,
	    18 Bit18,
	    19 Bit19,
	    20 Bit20,
	    21 Bit21,
	    22 Bit22,
	    23 Bit23,
	    24 Bit24,
	    25 Bit25,
	    26 Bit26,
	    27 Bit27,
	    28 Bit28,
	    29 Bit29,
	    30 Bit30,
	    31 Bit31,
	    32 Bit32,
	  ];
	  t_e_OpcUa_BaseStatus :
	  (
	    BS_Registered,
	    BS_Init,
	    BS_Ready,
	    BS_Invalid
	  )$UDINT;
	  t_e_OpcUa_DataChangeTrigger :
	  (
	    OpcUa_DataChangeTrigger_Status:=0,
	    OpcUa_DataChangeTrigger_StatusValue:=1,
	    OpcUa_DataChangeTrigger_StatusValueTimestamp:=2,
	    _OpcUa_DataChangeTrigger_MaxEnumerationValue:=2147483647
	  )$UDINT;
	  t_e_OpcUa_ExtensionObjectEncoding :
	  (
	    EOE_None,
	    EOE_Binary,
	    EOE_Xml,
	    EOE_EncodeableObject
	  )$UDINT;
	  t_e_OpcUa_NodeClass_Intern_c :
	  (
	    OpcUa_NodeClass_Unspecified,
	    OpcUa_NodeClass_Object,
	    OpcUa_NodeClass_Variable,
	    OpcUa_NodeClass_Method,
	    OpcUa_NodeClass_ObjectType,
	    OpcUa_NodeClass_VariableType,
	    OpcUa_NodeClass_ReferenceType,
	    OpcUa_NodeClass_DataType,
	    OpcUa_NodeClass_View,
	    _OpcUa_NodeClass_MaxEnumerationValue
	  )$UDINT;
#pragma pack(push, 1)
	  t_OPCUA_ByteString : STRUCT
	    Length : DINT;
	    Data : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  t_StructFieldDescriptor : STRUCT
	    Name : ^CHAR;
	    DataType : OPCUA_DataTypeId;
	    ArrayType : BYTE;
	    LasalSize : UDINT;
	    Next : ^t_StructFieldDescriptor;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tCertificateDatail : STRUCT
	    sIssuedFor : ^CHAR;
	    sIssuedBy : ^CHAR;
	    sValidFrom : ^CHAR;
	    sValidTo : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_PointerType_Enum :
	  (
	    Element:=0,
	    PointerToElement:=1,
	    PointerToServer:=2
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_Array : STRUCT
	    ArraySize : DINT;
	    PointerType : tOpcUa_PointerType_Enum;
	    List : _PVOIDL;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_Attributes_Enum :
	  (
	    OpcUa_Attributes_NodeId:=1,
	    OpcUa_Attributes_NodeClass:=2,
	    OpcUa_Attributes_BrowseName:=3,
	    OpcUa_Attributes_DisplayName:=4,
	    OpcUa_Attributes_Description:=5,
	    OpcUa_Attributes_WriteMask:=6,
	    OpcUa_Attributes_UserWriteMask:=7,
	    OpcUa_Attributes_IsAbstract:=8,
	    OpcUa_Attributes_Symmetric:=9,
	    OpcUa_Attributes_InverseName:=10,
	    OpcUa_Attributes_ContainsNoLoops:=11,
	    OpcUa_Attributes_EventNotifier:=12,
	    OpcUa_Attributes_Value:=13,
	    OpcUa_Attributes_DataType:=14,
	    OpcUa_Attributes_ValueRank:=15,
	    OpcUa_Attributes_ArrayDimension:=16,
	    OpcUa_Attributes_AccessLevel:=17,
	    OpcUa_Attributes_UserAccessLevel:=18,
	    OpcUa_Attributes_MinimumSamplingInterval:=19,
	    OpcUa_Attributes_Historizing:=20,
	    OpcUa_Attributes_Executable:=21,
	    OpcUa_Attributes_UserExecutable:=22,
	    OpcUa_Attributes_DataTypeDefinition:=23,
	    OpcUa_Attributes_RolePermissions:=24,
	    OpcUa_Attributes_UserRolePermissions:=25,
	    OpcUa_Attributes_AccessRestrictions:=26,
	    OpcUa_Attributes_AccessLevelEx:=27
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_QualifiedName : STRUCT
	    NamespaceIndex : UINT;
	    Reserved : UINT;
	    Name : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_RelativePathElement : STRUCT
	    ReferenceTypeId : OPCUA_NodeId;
	    IsInverse : BOOL;
	    IncludeSubtypes : BOOL;
	    TargetName : tOpcUa_QualifiedName;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_RelativePath : STRUCT
	    NoOfElements : DINT;
	    Elements : ^tOpcUa_RelativePathElement;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_BrowsePath : STRUCT
	    StartingNode : OPCUA_NodeId;
	    RelativePath : tOpcUa_RelativePath;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_BrowsePathAsString : STRUCT
	    StartingNode : OPCUA_NodeId;
	    RelativePath : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_BrowsePathTarget : STRUCT
	    TargetId : ^OPCUA_NodeId;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_BrowsePathResult : STRUCT
	    StatusCode : DINT;
	    NoOfTargets : DINT;
	    Targets : ^tOpcUa_BrowsePathTarget;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_String_Intern_c : STRUCT
	    flags : UDINT;
	    uLength : UDINT;
	    strContent : ^void;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_QualifiedName_Intern_c : STRUCT
	    NamespaceIndex : UINT;
	    Reserved : UINT;
	    Name : tOpcUa_String_Intern_c;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_NodeId_Intern_c : STRUCT
	    IdentifierType : UINT;
	    NamespaceIndex : UINT;
	    Identifier : tOpcUa_String_Intern_c;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_ExpandedNodeId_Intern_c : STRUCT
	    NodeId : tOpcUa_NodeId_Intern_c;
	    NamespaceUri : tOpcUa_String_Intern_c;
	    ServerIndex : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_LocalizedText_Intern_c : STRUCT
	    Locale : tOpcUa_String_Intern_c;
	    Text : tOpcUa_String_Intern_c;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  tOpcUa_ReferenceDescription_Intern_c : STRUCT
	    ReferenceTypeId : tOpcUa_NodeId_Intern_c;
	    IsForward : USINT;
	    NodeId : tOpcUa_ExpandedNodeId_Intern_c;
	    BrowseName : tOpcUa_QualifiedName_Intern_c;
	    DisplayName : tOpcUa_LocalizedText_Intern_c;
	    NodeClass : t_e_OpcUa_NodeClass_Intern_c;
	    TypeDefinition : tOpcUa_ExpandedNodeId_Intern_c;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_BrowseResult_Intern_c : STRUCT
	    StatusCode : UDINT;
	    ContinuationPoint : t_OPCUA_ByteString;
	    NoOfReferences : DINT;
	    References : ^tOpcUa_ReferenceDescription_Intern_c;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_ByteString : STRUCT
	    Length : DINT;
	    Data : ^USINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_CallMethodRequest : STRUCT
	    ObjectId : OPCUA_NodeId;
	    MethodId : OPCUA_NodeId;
	    NoOfInputArguments : DINT;
	    InputArguments : ^tOpcUa_Variant;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_CallMethodResult : STRUCT
	    StatusCode : UDINT;
	    NoOfInputArgumentResults : DINT;
	    InputArgumentResults : ^UDINT;
	    NoOfOutputArguments : DINT;
	    OutputArguments : ^tOpcUa_Variant;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_CallMethodsResponse : STRUCT
	    NoOfResults : DINT;
	    Results : ^tOpcUa_CallMethodResult;
	  END_STRUCT;
#pragma pack(pop)
	  tOPCUA_CertificateMode :
	  (
	    Reject:=0,
	    Trust:=1,
	    Revoke:=2,
	    Delete:=3
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_ContentFilterElement : STRUCT
	    NoOfFilterOperands : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_ContentFilter : STRUCT
	    NoOfElements : DINT;
	    Elements : ^tOpcUa_ContentFilterElement;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_FilterResult : STRUCT
	    NoOfSelectClauseResults : DINT;
	    SelectClauseResults : ^UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_MonitoredItemCreateResult : STRUCT
	    StatusCode : DINT;
	    MonitoredItemId : UDINT;
	    RevisedSamplingInterval : REAL;
	    RevisedQueueSize : UDINT;
	    EventFilterResult : tOpcUa_FilterResult;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_CreateMonitoredItemsResponse : STRUCT
	    NoOfResults : DINT;
	    Results : ^tOpcUa_MonitoredItemCreateResult;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_CreateSubscriptionResponse : STRUCT
	    SubscriptionId : UDINT;
	    RevisedPublishingInterval : REAL;
	    RevisedLifetimeCount : UDINT;
	    RevisedMaxKeepAliveCount : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_DataChangeFilter : STRUCT
	    Trigger : t_e_OpcUa_DataChangeTrigger;
	    DeadbandType : UDINT;
	    DeadbandValue : ARRAY [0..1] OF DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_DataValue : STRUCT
	    StatusCode : UDINT;
	    Value : tOpcUa_Variant;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_MonitoredItemNotification : STRUCT
	    ClientHandle : UDINT;
	    Value : tOpcUa_DataValue;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_DataChangeNotification : STRUCT
	    NoOfMonitoredItems : DINT;
	    MonitoredItems : ^tOpcUa_MonitoredItemNotification;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  tOpcUa_DataElementExtern : STRUCT
	    pLabel : ^CHAR;
	    LasalID : UDINT;
	    Station : DINT;
	    TypeID : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_DataLog : STRUCT
	    hItem : UDINT;
	    hPrimaryKey : DINT;
	    NodeId : OPCUA_NodeId;
	    SamplingRate : ARRAY [0..1] OF DINT;
	    Filter : tOpcUa_DataChangeFilter;
	    Active_used : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_DataTypes_Enum :
	  (
	    OpcUa_DataType_Boolean:=1,
	    OpcUa_DataType_SByte:=2,
	    OpcUa_DataType_Byte:=3,
	    OpcUa_DataType_Int16:=4,
	    OpcUa_DataType_UInt16:=5,
	    OpcUa_DataType_Int32:=6,
	    OpcUa_DataType_UInt32:=7,
	    OpcUa_DataType_Int64:=8,
	    OpcUa_DataType_UInt64:=9,
	    OpcUa_DataType_Float:=10,
	    OpcUa_DataType_Double:=11,
	    OpcUa_DataType_String:=12,
	    OpcUa_DataType_DateTime:=13,
	    OpcUa_DataType_Guid:=14,
	    OpcUa_DataType_ByteString:=15,
	    OpcUa_DataType_XmlElement:=16,
	    OpcUa_DataType_NodeId:=17,
	    OpcUa_DataType_ExpandedNodeId:=18,
	    OpcUa_DataType_StatusCode:=19,
	    OpcUa_DataType_QualifiedName:=20,
	    OpcUa_DataType_LocalizedText:=21,
	    OpcUa_DataType_ExtensionObject:=22,
	    OpcUa_DataType_DataValue:=23,
	    OpcUa_DataType_Variant:=24,
	    OpcUa_DataType_DiagnosticInfo:=25
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_DateTime : STRUCT
	    dwLowDateTime : UDINT;
	    dwHighDateTime : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  tOpcUa_DataValueEx : STRUCT
	    Value : tOpcUa_Variant;
	    StatusCode : UDINT;
	    SourceTimestamp : tOpcUa_DateTime;
	    ServerTimestamp : tOpcUa_DateTime;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_DeleteSubscriptionsResponse : STRUCT
	    NoOfResults : DINT;
	    Results : ^UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_EnumValue : STRUCT
	    value : int64;
	    displayName : tOPCUA_LocalizedText;
	    description : tOPCUA_LocalizedText;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_EUInformation : STRUCT
	    NamespaceUri : ^CHAR;
	    UnitId : DINT;
	    DisplayName : ^CHAR;
	    Description : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_EventFieldList : STRUCT
	    ClientHandle : UDINT;
	    NoOfEventFields : DINT;
	    EventFields : ^tOpcUa_Variant;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_SimpleAttributeOperand : STRUCT
	    TypeDefinitionId : OPCUA_NodeId;
	    NoOfBrowsePath : DINT;
	    BrowsePath : ^tOpcUa_QualifiedName;
	    AttributeId : UDINT;
	    IndexRange : ^CHAR;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_EventFilter : STRUCT
	    NoOfSelectClauses : DINT;
	    SelectClauses : ^tOpcUa_SimpleAttributeOperand;
	    WhereClause : tOpcUa_ContentFilter;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_EventNotificationList : STRUCT
	    NoOfEvents : DINT;
	    Events : ^tOpcUa_EventFieldList;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_ExtensionObject : STRUCT
	    TypeId : OPCUA_NodeId;
	    Object : _PVOIDL;
	    BinaryEncodingTypeId : UDINT;
	    XMLEncodingTypeId : UDINT;
	    AllocationSize : UDINT;
	    Encoding : t_e_OpcUa_ExtensionObjectEncoding;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_HistoryData : STRUCT
	    NoOfDataValues : DINT;
	    DataValues : ^tOpcUa_DataValueEx;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_HistoryReadResult : STRUCT
	    StatusCode : UDINT;
	    ContinuationPoint : t_OPCUA_ByteString;
	    HistoryData : tOpcUa_HistoryData;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_MemoryAccessMode_Enum :
	  (
	    MemoryAccessMode_Server,
	    MemoryAccessMode_ServerToMemory,
	    MemoryAccessMode_Memory,
	    MemoryAccessMode_Station:=3
	  )$SINT;
#pragma pack(push, 1)
	  tOpcUa_ModifySubscriptionResponse : STRUCT
	    RevisedPublishingInterval : REAL;
	    RevisedLifetimeCount : UDINT;
	    RevisedMaxKeepAliveCount : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_ReadValueId : STRUCT
	    NodeId : OPCUA_NodeId;
	    AttributeId : UDINT;
	    IndexRange : ^CHAR;
	    DataEncoding : ^tOpcUa_QualifiedName;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_MonitoringMode_Enum :
	  (
	    MonitoringMode_Disabled:=0,
	    MonitoringMode_Sampling:=1,
	    MonitoringMode_Reporting:=2
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_MonitoringParameters : STRUCT
	    ClientHandle : UDINT;
	    SamplingInterval : REAL;
	    QueueSize : UDINT;
	    DiscardOldest : BOOL;
	    Filter : ^tOpcUa_EventFilter;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_MonitoredItemCreateRequest : STRUCT
	    ItemToMonitor : tOpcUa_ReadValueId;
	    MonitoringMode : tOpcUa_MonitoringMode_Enum;
	    RequestedParameters : tOpcUa_MonitoringParameters;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_NodeClass_Enum :
	  (
	    OpcUa_NodeClass_Unspecified:=0,
	    OpcUa_NodeClass_Object:=1,
	    OpcUa_NodeClass_Variable:=2,
	    OpcUa_NodeClass_Method:=4,
	    OpcUa_NodeClass_ObjectType:=8,
	    OpcUa_NodeClass_VariableType:=16,
	    OpcUa_NodeClass_ReferenceType:=32,
	    OpcUa_NodeClass_DataType:=64,
	    OpcUa_NodeClass_View:=128,
	    OpcUa_NodeClass_Invalid:=4294967295
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_NotificationMessage : STRUCT
	    SequenceNumber : UDINT;
	    NoOfNotificationData : DINT;
	    NotificationData : ^tOpcUa_ExtensionObject;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_PublishResponse : STRUCT
	    SubscriptionId : UDINT;
	    NoOfAvailableSequenceNumbers : DINT;
	    AvailableSequenceNumbers : ^UDINT;
	    MoreNotifications : BOOL;
	    NotificationMessage : tOpcUa_NotificationMessage;
	    NoOfResults : DINT;
	    Results : ^UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_Range : STRUCT
	    Low : REAL;
	    High : REAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_SubscriptionAcknowledgement : STRUCT
	    SubscriptionId : UDINT;
	    SequenceNumber : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	  tOpcUa_TimestampsToReturn_Enum :
	  (
	    TimestampsToReturn_Source:=0,
	    TimestampsToReturn_Server:=1,
	    TimestampsToReturn_Both:=2,
	    TimestampsToReturn_Neither:=3,
	    TimestampsToReturn_Invalid:=4
	  )$UDINT;
#pragma pack(push, 1)
	  tOpcUa_TimeZoneDataType : STRUCT
	    Offset : INT;
	    DaylightSavingInOffset : BOOL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  tOpcUa_TranslateBrowsePathsToNodeIdsResponse : STRUCT
	    NoOfResults : DINT;
	    Results : ^tOpcUa_BrowsePathResult;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  uint64 : STRUCT
	    low : UDINT;
	    high : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
OPC_UA_DataLoggerBase : CLASS_PUBLIC
	TYPE
	  t_e_OpcUa_LoggerType :
	  (
	    LT_Invalid,
	    LT_RAM,
	    LT_SRAM
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
OPC_UA_EncryptionBase : CLASS_PUBLIC
#include "..\Class\OPC_UA_EncryptionBase\custom\encryption_utilities_st.h"
	TYPE
	  CmdClassSvr :
	  (
	    GetVersion
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
SafetyBaseFSoE : CLASS_PUBLIC
#include "..\Source\interfaces\lsl_st_safety.h"
#include "..\Class\SafetyManager\SafetyManager.h"
#include "..\Source\BusInterface.h"
#include "..\Class\SafetyBaseFSoE\SafetyBaseFSoE.h"
#include "..\Source\interfaces\lsl_st_hardwaretree.h"
	TYPE
#pragma pack(push, 1)
	  SDOHeader : STRUCT
	    StdHeader : t_SDOStdHeader;
	    SrcAdr : HDINT;
	    DstAdr : HDINT;
	    SessId : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
SafetyCDIAS_Base : CLASS_PUBLIC
#include "..\Class\SafetyCDIAS_Base\SafetyCDIAS_Base.h"
#include "..\Source\interfaces\lsl_st_safety.h"
#include "..\Class\SafetyManager\SafetyManager.h"
	TYPE
	  FrameTypeType : BSINT
	  [
	    1 Cfg,
	    2 ToP,
	    3 Standard,
	    4 PDO,
	    5 TDO,
	    6 Reserved1,
	    7 Reserved2,
	    8 Response,
	  ];
#pragma pack(push, 1)
	  SDOStdHeader : STRUCT
	    CRC : UDINT;
	    Cmd : USINT;
	    Typ : FrameTypeType;
	    SeqNr : USINT;
	    Len : USINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  SDOHeader : STRUCT
	    StdHeader : SDOStdHeader;
	    SrcAdr : HDINT;
	    DstAdr : HDINT;
	    SessId : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
SafetyUDP : CLASS_PUBLIC
	TYPE
	  _FSM_UDP_ERROR :
	  (
	    _NO_ERROR_UDP_ERROR:=0,
	    _INIT_TCP_USER_UDP_ERROR:=4294967295,
	    _NO_IP_ADDRESS_UDP_ERROR:=4294967294,
	    _NO_MEMORY_SOCKET_UDP_ERROR:=4294967293,
	    _NO_MEMORY_SENDBUFFER_UDP_ERROR:=4294967292,
	    _INVALID_HANDLE_UDP_ERROR:=4294967291,
	    _SHUTDOWN_UDP_ERROR:=4294967290,
	    _CLOSESOCKET_UDP_ERROR:=4294967289,
	    _ALLOCATE_SOCKET_UDP_ERROR:=4294967288,
	    _SET_BIND_UDP_ERROR:=4294967287,
	    _RECV_UDP_ERROR:=4294967286,
	    _SEND_UDP_ERROR:=4294967285,
	    _NO_LOCAL_IP_UDP_ERROR:=4294967284,
	    _NO_DESTINATION_IP_UDP_ERROR:=4294967283,
	    _INVALID_UDP_PORT_UDP_ERROR,
	    _INVALID_INTERFACE_NUMBER_UDP_ERROR,
	    _NO_MEMORY_RECEIVE_BUFFER_UDP_ERROR,
	    _NO_MEMORY_CONNECTION_BUFFER_UDP_ERROR
	  )$DINT;
	  _FSM_UDP_USER :
	  (
	    _STATE_INIT_UDP,
	    _STATE_IDLE_UDP,
	    _STATE_SOCK_UDP,
	    _STATE_CONNECT_UDP,
	    _STATE_ONLY_SEND_UDP,
	    _STATE_RECV_UDP,
	    _STATE_SEND_UDP,
	    _STATE_SHUTDOWN_UDP,
	    _STATE_CLOSE_SOCK_UDP,
	    _STATE_ERROR_UDP
	  )$UDINT;
	  _INITSTEPS :
	  (
	    _NO_OPERATION,
	    _ADD_SOCKET,
	    _CHECK_IF_SOCKET_OPEN,
	    _BIND_SOCKET,
	    _CLOSE_CON
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
VirtualBaseInit : CLASS_PUBLIC
	TYPE
	  CmdData :
	  (
	    GET_ADD_INFO,
	    READ_DATA,
	    WRITE_DATA,
	    READ_DATA_OFF,
	    WRITE_DATA_OFF
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)

#RE_IN_DE
